/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package hawkadvertisng;

/**
 *
 * @author AbdulRehman
 */
public class SettingsNormal extends javax.swing.JPanel {

    /**
     * Creates new form SettingsNormal
     */
    MainWindow Homeh;
    public SettingsNormal(MainWindow home ,String User) {
        initComponents();
        Homeh=home;
        this.User.setText(User);
            
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        User = new javax.swing.JTextField();
        RePass = new javax.swing.JPasswordField();
        Pass = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        hawklogo = new javax.swing.JLabel();
        home = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1024, 768));
        setMinimumSize(new java.awt.Dimension(1024, 768));
        setName(""); // NOI18N
        setLayout(null);

        jPanel1.setBackground(new java.awt.Color(25, 31, 36));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        jLabel2.setText("Password:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 70, 70, 20);

        jLabel3.setText("Re-Password:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 120, 70, 20);

        jLabel4.setText("User Name:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 30, 70, 20);

        jButton2.setText("Okay");
        jButton2.setOpaque(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(130, 170, 80, 23);

        jButton3.setText("Cancel");
        jButton3.setOpaque(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(230, 170, 80, 23);

        User.setEditable(false);
        User.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserActionPerformed(evt);
            }
        });
        jPanel1.add(User);
        User.setBounds(90, 30, 140, 20);
        jPanel1.add(RePass);
        RePass.setBounds(90, 120, 140, 20);
        jPanel1.add(Pass);
        Pass.setBounds(90, 70, 140, 20);

        add(jPanel1);
        jPanel1.setBounds(20, 160, 500, 300);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setText("Change Password:");
        add(jLabel5);
        jLabel5.setBounds(390, 70, 210, 60);

        hawklogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/hawk_logo.png"))); // NOI18N
        add(hawklogo);
        hawklogo.setBounds(0, 0, 350, 100);

        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/button_home.png"))); // NOI18N
        home.setText("jLabel10");
        home.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        home.setMaximumSize(new java.awt.Dimension(80, 80));
        home.setMinimumSize(new java.awt.Dimension(80, 80));
        home.setPreferredSize(new java.awt.Dimension(80, 80));
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });
        add(home);
        home.setBounds(940, 20, 80, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/homepage_background.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 1024, 768);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        if(Valid())
        {
            DataBase db =new DataBase();
            db.connectToDB("hawklogin");
            db.runQuerry("Update `info` set `Passwd`='"+Pass.getText()+"' where User = "+User.getText().trim());
            db.DisconnectFromDB();
            Pass.setText("");
            RePass.setText("");
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed
    
    public boolean Valid()
    {  
       
        if(User.getText().isEmpty() || Pass.getText().isEmpty()) 
        {
          return false;
        }
        
        if ( !Pass.getText().contentEquals(RePass.getText() )   )
        {
           
         return false ;
        } 
        
      
        return true;
    }
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void UserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserActionPerformed

    }//GEN-LAST:event_UserActionPerformed

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        // TODO add your handling code here:
        Homeh.ShowWindow(new HomePage(Homeh));
    }//GEN-LAST:event_homeMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Pass;
    private javax.swing.JPasswordField RePass;
    private javax.swing.JTextField User;
    private javax.swing.JLabel hawklogo;
    private javax.swing.JLabel home;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
